#!/bin/bash

CONFIG_FILE=/etc/insaned/events/config
DEVICE=${DEVICE-${1}}
if [ -z "$FOLDER" ] ; then
  FOLDER=$(mktemp -d)
fi
PDF_FILE=$(date --iso-8601=seconds).pdf

set -e
source $CONFIG_FILE
set +e

cd $FOLDER
scanadf -d ${DEVICE} -N --resolution ${RESOLUTION-200} --source "ADF Duplex"
if [ ! -f image-0001 ] ; then
    exit 0;
fi
convert image* -adjoin $PDF_FILE
rm image*
if [ -n "{$WEBDAV_URL}" ] ; then
  echo "Uploading $PDF_FILE to $WEBDAV_URL"
  curl -T $PDF_FILE -u $WEBDAV_USER_PASS $WEBDAV_URL
fi