#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${DIR}/load_config.sh"

export SCAN_TYPE="$BUTTON3_TYPE"
export SCAN_OPTIONS="$BUTTON3_OPTIONS"
export SCAN_SOURCE="$BUTTON3_SOURCE"

"${DIR}/scan.sh" "$@"