#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

DEFAULT_OPTIONS_FILE="${DIR}/default_options"
CONFIG_FILE="${DIR}/config"
set -e
source "${DEFAULT_OPTIONS_FILE}"
if [ -f "${CONFIG_FILE}" ] ; then 
  source "${CONFIG_FILE}"
fi
set +e

${EXEC_ON}