#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${DIR}/load_config.sh"

export SCAN_TYPE="$BUTTON1_TYPE"
export SCAN_OPTIONS="$BUTTON1_OPTIONS"
export SCAN_SOURCE="$BUTTON1_SOURCE"

"${DIR}/scan.sh" "$@"
