#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

DEFAULT_OPTIONS_FILE="${DIR}/default_options"
CONFIG_FILE="${DIR}/config"

set -e
source "${DEFAULT_OPTIONS_FILE}"
if [ -f "${CONFIG_FILE}" ] ; then 
  source "${CONFIG_FILE}"
fi
set +e

export WEBDAV_USER_PASS
export WEBDAV_URL
export RSYNC_OPTIONS
export RSYNC_PATH
export SCAN_TYPE="$BUTTON2_TYPE"
export SCAN_OPTIONS="$BUTTON2_OPTIONS"
export SCAN_SOURCE="$BUTTON2_SOURCE"

"${DIR}/scan.sh" "$@"
